In [1]:
import pandas as pd

In [2]:
# Load the data
counts = pd.read_csv('input/GSE247186_counts_raw_gene_name.txt', sep='\t', index_col=0)
meta = pd.read_csv('input/GSE247186_series_matrix.txt', sep='\t', index_col=0, skiprows=37)

counts.head()

,3399-OG-10,3399-OG-13,3399-OG-14,3399-OG-15,3399-OG-16,3399-OG-19,3399-OG-20,3399-OG-31,3399-OG-32,3399-OG-33,3399-OG-34,3399-OG-9
DDX11L1,0,0,0,0,0,0,0,0,0,0,0,0
WASH7P,0,0,0,0,0,0,0,0,0,0,0,1
MIR6859-1,0,0,0,0,0,0,0,0,0,0,0,0
MIR1302-2HG,0,0,0,0,0,0,0,0,0,0,0,0
MIR1302-2,0,0,0,0,0,0,0,0,0,0,0,0

In [3]:
meta.head()

,COVID-19_NT#3,COVID-19_LPS#3,CONTROL_NT#1,CONTROL_LPS#1,COVID-19_NT#2,COVID-19_LPS#2,COVID-19_NT#1,COVID-19_LPS#1,CONTROL_NT#3,CONTROL_LPS#3,CONTROL_NT#2,CONTROL_LPS#2
!Sample_title,,,,,,,,,,,,
!Sample_geo_accession,GSM7884936,GSM7884937,GSM7884938,GSM7884939,GSM7884940,GSM7884941,GSM7884942,GSM7884943,GSM7884944,GSM7884945,GSM7884946,GSM7884947
!Sample_status,Public on Jan 23 2024,Public on Jan 23 2024,Public on Jan 23 2024,Public on Jan 23 2024,Public on Jan 23 2024,Public on Jan 23 2024,Public on Jan 23 2024,Public on Jan 23 2024,Public on Jan 23 2024,Public on Jan 23 2024,Public on Jan 23 2024,Public on Jan 23 2024
!Sample_submission_date,Nov 07 2023,Nov 07 2023,Nov 07 2023,Nov 07 2023,Nov 07 2023,Nov 07 2023,Nov 07 2023,Nov 07 2023,Nov 07 2023,Nov 07 2023,Nov 07 2023,Nov 07 2023
!Sample_last_update_date,Jan 26 2024,Jan 26 2024,Jan 26 2024,Jan 26 2024,Jan 26 2024,Jan 26 2024,Jan 26 2024,Jan 26 2024,Jan 26 2024,Jan 26 2024,Jan 26 2024,Jan 26 2024
!Sample_type,SRA,SRA,SRA,SRA,SRA,SRA,SRA,SRA,SRA,SRA,SRA,SRA

In [4]:
gsm_ids = meta.loc[['!Sample_geo_accession', '!Sample_description']]
gsm_ids

,COVID-19_NT#3,COVID-19_LPS#3,CONTROL_NT#1,CONTROL_LPS#1,COVID-19_NT#2,COVID-19_LPS#2,COVID-19_NT#1,COVID-19_LPS#1,CONTROL_NT#3,CONTROL_LPS#3,CONTROL_NT#2,CONTROL_LPS#2
!Sample_title,,,,,,,,,,,,
!Sample_geo_accession,GSM7884936,GSM7884937,GSM7884938,GSM7884939,GSM7884940,GSM7884941,GSM7884942,GSM7884943,GSM7884944,GSM7884945,GSM7884946,GSM7884947
!Sample_description,3399-OG-9,3399-OG-10,3399-OG-13,3399-OG-14,3399-OG-15,3399-OG-16,3399-OG-19,3399-OG-20,3399-OG-31,3399-OG-32,3399-OG-33,3399-OG-34